    CREATE DATABASE inventorydb;
CURRENT_TIMESTAMP
    USE inventorydb;

    CREATE TABLE products (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100)NOT NULL,
     quantity INT NOT NULL , created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);